import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import "@fontsource/roboto-mono"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rainee's Design Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello! I'm Rainee
          <br/>A UX Researcher &amp; Designer 
          <br/>from San Diego, CA.
        </h1>

        <p className={styles.description}>
          + Currently a Researcher at UC San Diego's 
          <br/><u>Healthcare Robotics Lab.</u>
        </p>

        {/* horizontal linebreak */}
        <header className={styles.header}></header>



        <div className={styles.grid}>
          <a href="https://medium.com/@pei.rainee/depop-redesign-73b1e2f7d8c5" className={styles.card} target="_blank">
            <h2>1. DEPOP REDESIGN</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="/case-studies/kini-koffee" className={styles.card}>
            <h2></h2>
            <p></p>
          </a>

          <a href="/case-studies/kini-koffee" className={styles.card}>
            <h2>2. KINI KOFFEE</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="/case-studies/kini-koffee" className={styles.card}>
            <h2></h2>
            <p></p>
          </a>

          <a href="/case-studies/kini-koffee" className={styles.card}>
            <h2>3. DESIGN CO</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

        </div>
      </main>
    </div>
  )
}
